"""Contrat public de l'installation distante par SSH."""

from __future__ import annotations

import base64
import hashlib
import json
import sys
from dataclasses import dataclass
from types import SimpleNamespace

import pytest

from plugarr.remote_install import (
    REMOTE_ENTRYPOINT,
    FingerprintMismatch,
    RemoteCredentials,
    RemoteDeployment,
    RemoteProjectState,
    RemoteTarget,
    connect_paramiko,
    deploy,
    inspect_project,
    probe,
)
from plugarr.remote_install import test_vpn as run_remote_vpn_test


@dataclass
class ProbeSession:
    """Adaptateur SSH de test : la frontiere reseau est remplacee, pas PlugArr."""

    fingerprint: str = "SHA256:serveur-maison"

    def run(self, _command: str, *, stdin: bytes | None = None):
        return (
            0,
            (
                "system=Linux\nmachine=aarch64\nuid=1000\ngid=10\n"
                "home=/home/yannick\ndocker=29.8.1"
            ),
            "",
        )

    def close(self):
        pass


@dataclass
class DeploySession:
    """Machine SSH observable depuis le contrat public de deploiement."""

    fingerprint: str = "SHA256:serveur-maison"

    def __post_init__(self):
        self.commands: list[str] = []
        self.files: dict[str, tuple[bytes, int]] = {}

    def run(self, command: str, *, stdin: bytes | None = None):
        self.commands.append(command)
        if "stat -c %g /var/run/docker.sock" in command:
            return 0, "sock_gid=998\n", ""
        return (
            0,
            (
                '{"kind":"progress","phase":"preflight","message":"Docker pret"}\n'
                '{"kind":"done","status":"done"}'
            ),
            "",
        )

    def upload(self, path: str, data: bytes, *, mode: int = 0o600):
        self.files[path] = (data, mode)

    def close(self):
        pass


def test_probe_decrit_le_serveur_sans_exposer_le_secret():
    target = RemoteTarget(host="192.168.1.50", port=22, username="yannick")
    credentials = RemoteCredentials(password="mot-de-passe-tres-secret")

    result = probe(target, credentials, connect=lambda *_: ProbeSession())

    assert result.fingerprint == "SHA256:serveur-maison"
    assert result.system == "Linux"
    assert result.machine == "aarch64"
    assert (result.uid, result.gid) == (1000, 10)
    assert result.home == "/home/yannick"
    assert result.docker_version == "29.8.1"
    assert result.ready
    assert "mot-de-passe-tres-secret" not in repr(result)


def test_probe_refuse_une_cle_serveur_differente_de_celle_confirmee():
    target = RemoteTarget(
        host="192.168.1.50",
        port=22,
        username="yannick",
        expected_fingerprint="SHA256:cle-confirmee",
    )

    with pytest.raises(FingerprintMismatch, match="empreinte SSH a change"):
        probe(target, RemoteCredentials(password="secret"), connect=lambda *_: ProbeSession())


def test_inspection_reconnait_une_pile_plugarr_sans_la_modifier():
    class ExistingSession(ProbeSession):
        def __post_init__(self):
            self.commands = []

        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            return 0, "exists=1\nstack_sha=abc123\nmanaged=1\n", ""

    session = ExistingSession()
    session.__post_init__()

    state = inspect_project(
        RemoteTarget(
            host="nas.local",
            username="yannick",
            expected_fingerprint=session.fingerprint,
        ),
        RemoteCredentials(password="secret"),
        "/home/yannick/plugarr",
        connect=lambda *_: session,
    )

    assert state == RemoteProjectState(exists=True, managed=True, stack_sha="abc123")
    assert len(session.commands) == 1
    assert "Genere par|Generated by" in session.commands[0]
    assert "plugarr.managed" not in session.commands[0]


def test_inspection_extrait_seulement_le_resume_necessaire_au_reset():
    stack = (
        b"# Genere par plugarr - test\nproject_name: plugarr\n"
        b"config_root: /srv/plugarr/config\ndata_root: /srv/data\n"
        b"services:\n  sonarr: {}\n  qbittorrent: {}\n"
    )

    class ExistingSession(ProbeSession):
        def run(self, _command: str, *, stdin: bytes | None = None):
            return 0, (
                "exists=1\nmanaged=1\n"
                f"stack_sha={hashlib.sha256(stack).hexdigest()}\n"
                f"stack_b64={base64.b64encode(stack).decode()}\n"
            ), ""

    session = ExistingSession()
    state = inspect_project(
        RemoteTarget(host="nas.local", username="yannick", expected_fingerprint=session.fingerprint),
        RemoteCredentials(password="secret"),
        "/srv/plugarr",
        connect=lambda *_: session,
    )

    assert state.managed
    assert state.services == ("sonarr", "qbittorrent")
    assert state.config_root == "/srv/plugarr/config"
    assert state.data_root == "/srv/data"


def test_deploy_envoie_la_stack_et_retransmet_la_progression_sans_secret_ssh():
    session = DeploySession()
    target = RemoteTarget(
        host="192.168.1.50",
        username="yannick",
        expected_fingerprint=session.fingerprint,
    )
    credentials = RemoteCredentials(password="secret-ssh-a-ne-jamais-copier")
    deployment = RemoteDeployment(
        project_dir="/home/yannick/plugarr",
        config_root="/home/yannick/plugarr/config",
        data_root="/srv/data",
        uid=1000,
        gid=10,
        stack_yaml="version: 1\nservices: {}\n",
        image="ghcr.io/example/plugarr:test",
    )
    events: list[dict[str, object]] = []

    result = deploy(
        target,
        credentials,
        deployment,
        connect=lambda *_: session,
        on_event=events.append,
    )

    assert result.status == "done"
    assert events == [
        {"kind": "progress", "phase": "preflight", "message": "Docker pret"},
        {"kind": "done", "status": "done"},
    ]
    stack = session.files["/home/yannick/plugarr/stack.yml"]
    assert stack == (b"version: 1\nservices: {}\n", 0o600)
    assert "/home/yannick/plugarr/.plugarr-remote-entry.py" in session.files
    trace = repr(session.commands) + repr(session.files) + repr(result)
    assert "secret-ssh-a-ne-jamais-copier" not in trace


def test_entree_distante_accepte_ancien_catalogue_sans_conteneurs_techniques(
    monkeypatch, capsys
):
    """Le lanceur envoye par l'EXE corrige l'image admin deja publiee."""
    cfg = SimpleNamespace(remote_access=SimpleNamespace(mode="local"), services={})

    def old_get(service_id):
        if service_id == "sonarr":
            return SimpleNamespace(display_name="Sonarr")
        raise KeyError(f"service inconnu: {service_id}")

    catalog = SimpleNamespace(get=old_get)
    checked = []

    def old_install(_cfg, _project_dir, *, on_progress, on_step):
        for service_id in ("sonarr", "docker-proxy", "veille", "console"):
            checked.append(catalog.get(service_id).display_name)

    old_orchestrator = SimpleNamespace(
        catalog=catalog,
        preflight=lambda _cfg, _dir: [],
        install=old_install,
    )
    fake_package = SimpleNamespace(
        migrations=SimpleNamespace(lire=lambda _path: (cfg, [])),
        orchestrator=old_orchestrator,
        remote_access=SimpleNamespace(),
    )
    monkeypatch.setitem(sys.modules, "plugarr", fake_package)
    monkeypatch.setattr(sys, "argv", ["remote-entry", "/srv/plugarr", "install"])

    with pytest.raises(SystemExit) as result:
        exec(REMOTE_ENTRYPOINT, {"__name__": "__main__"})  # noqa: S102

    assert result.value.code == 0
    assert checked == ["Sonarr", "docker-proxy", "veille", "console"]
    assert catalog.get is old_get
    assert json.loads(capsys.readouterr().out.splitlines()[-1]) == {
        "kind": "done",
        "status": "done",
    }


def test_entree_reset_ne_touche_qu_a_l_etat_de_l_ancienne_pile(tmp_path, monkeypatch, capsys):
    old_bytes = b"ancienne pile"
    old_sha = hashlib.sha256(old_bytes).hexdigest()
    backup = tmp_path / f".stack-before-remote-{old_sha[:16]}.yml"
    backup.write_bytes(old_bytes)
    root = str(tmp_path / "config")
    data = str(tmp_path / "data")
    previous = SimpleNamespace(
        project_name="plugarr", config_root=root, data_root=data, services={"qui": object()}
    )
    current = SimpleNamespace(
        project_name="plugarr", config_root=root, data_root=data,
        services={}, remote_access=SimpleNamespace(mode="local"),
    )
    removed = []
    old_catalog = SimpleNamespace(STARTUP_ORDER=("qui",), get=lambda _sid: SimpleNamespace(display_name="qui"))
    old_orchestrator = SimpleNamespace(
        catalog=old_catalog, preflight=lambda *_: [], existing_configs=lambda _cfg: ["qui"],
        reset_installation_configs=lambda cfg, path, ids: removed.append(
            (cfg, path, ids)
        ) or [path / "config"],
        install=lambda *_args, **_kwargs: [], _compose_service_name=lambda sid: sid,
    )
    fake_package = SimpleNamespace(
        migrations=SimpleNamespace(lire=lambda path: (current if path.name == "stack.yml" else previous, [])),
        orchestrator=old_orchestrator, remote_access=SimpleNamespace(), catalog=old_catalog,
    )
    monkeypatch.setitem(sys.modules, "plugarr", fake_package)
    monkeypatch.setattr(
        sys, "argv",
        ["remote-entry", str(tmp_path), "reset-install", old_sha, "plugarr:admin"],
    )

    with pytest.raises(SystemExit) as result:
        exec(REMOTE_ENTRYPOINT, {"__name__": "__main__"})  # noqa: S102

    assert result.value.code == 0
    assert removed == [(previous, tmp_path, ["qui"])]
    assert json.loads(capsys.readouterr().out.splitlines()[-1]) == {"kind": "done", "status": "done"}


def test_nettoyage_distant_root_est_borne_au_dossier_du_service(tmp_path, monkeypatch):
    dossier = tmp_path / "audiobookshelf"
    sous_dossier = dossier / "config"
    sous_dossier.mkdir(parents=True)
    (sous_dossier / "db.sqlite").write_text("ancien", encoding="utf-8")
    media = tmp_path / "media" / "livre.m4b"
    media.parent.mkdir()
    media.write_text("a garder", encoding="utf-8")
    scope = {"__name__": "remote_test"}
    exec(REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102
    commands = []

    def fake_run(command, **kwargs):
        commands.append((command, kwargs))
        (sous_dossier / "db.sqlite").unlink()
        sous_dossier.rmdir()
        return SimpleNamespace(returncode=0, stderr="")

    monkeypatch.setattr(scope["subprocess"], "run", fake_run)
    scope["remove_root_owned_config"](dossier, "plugarr:admin")

    assert not dossier.exists()
    assert media.read_text(encoding="utf-8") == "a garder"
    command, kwargs = commands[0]
    assert command[command.index("--mount") + 1] == (
        f"type=bind,src={dossier},dst=/plugarr-reset"
    )
    assert command[command.index("--user") + 1] == "0:0"
    assert command[command.index("--entrypoint") + 1] == "python"
    assert command[command.index("--entrypoint") + 2] == "plugarr:admin"
    assert kwargs["timeout"] == 120


def test_reset_distant_reessaie_sans_argument_inconnu_pour_l_image_publiee(
    tmp_path, monkeypatch
):
    from plugarr import orchestrator

    config_root = tmp_path / "config"
    dossier = config_root / "audiobookshelf"
    blocked = dossier / "config"
    blocked.mkdir(parents=True)
    media = tmp_path / "data" / "media" / "livre.m4b"
    media.parent.mkdir(parents=True)
    media.write_text("a garder", encoding="utf-8")
    previous = SimpleNamespace(
        config_root=str(config_root),
        config_path=lambda _sid: str(dossier),
    )
    calls = []

    def old_image_reset(cfg, project, ids):
        calls.append((cfg, project, list(ids)))
        if len(calls) == 1:
            raise PermissionError(13, "Permission denied", str(blocked))
        return []

    monkeypatch.setattr(orchestrator, "reset_installation_configs", old_image_reset)
    scope = {"__name__": "remote_test"}
    exec(REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102
    cleaned = []
    scope["remove_root_owned_config"] = lambda path, image: cleaned.append((path, image))

    scope["reset_existing_configs"](
        previous, tmp_path, ["audiobookshelf"], "plugarr:admin"
    )

    assert [ids for _cfg, _project, ids in calls] == [
        ["audiobookshelf"], []
    ]
    assert cleaned == [(dossier.resolve(), "plugarr:admin")]
    assert media.read_text(encoding="utf-8") == "a garder"


def test_reset_distant_refuse_un_nettoyage_hors_configuration(tmp_path, monkeypatch):
    from plugarr import orchestrator

    config_root = tmp_path / "config"
    dossier = config_root / "audiobookshelf"
    dossier.mkdir(parents=True)
    media = tmp_path / "data" / "media" / "livre.m4b"
    media.parent.mkdir(parents=True)
    media.write_text("a garder", encoding="utf-8")
    previous = SimpleNamespace(
        config_root=str(config_root),
        config_path=lambda _sid: str(dossier),
    )

    def denied(_cfg, _project, _ids):
        raise PermissionError(13, "Permission denied", str(media))

    monkeypatch.setattr(orchestrator, "reset_installation_configs", denied)
    scope = {"__name__": "remote_test"}
    exec(REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102
    cleaned = []
    scope["remove_root_owned_config"] = lambda path, image: cleaned.append((path, image))

    with pytest.raises(PermissionError):
        scope["reset_existing_configs"](
            previous, tmp_path, ["audiobookshelf"], "plugarr:admin"
        )

    assert cleaned == []
    assert media.read_text(encoding="utf-8") == "a garder"


def test_entree_distante_reprend_la_cle_sabnzbd_du_fichier_existant(tmp_path):
    from plugarr import remote_install

    config = tmp_path / "sabnzbd"
    config.mkdir()
    (config / "sabnzbd.ini").write_text(
        "[misc]\napi_key = " + "a" * 32 + "\nnzb_key = " + "b" * 32 + "\n",
        encoding="utf-8",
    )
    instance = SimpleNamespace(api_key="nouvelle", password="nouvelle")
    cfg = SimpleNamespace(
        services={"sabnzbd": instance},
        config_path=lambda _service: str(config),
    )
    scope = {"__name__": "remote_test"}
    exec(remote_install.REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102

    scope["reuse_sabnzbd_key"](cfg)

    assert instance.api_key == "a" * 32
    assert instance.password == "a" * 32


def test_entree_distante_aligne_la_cle_sabnzbd_pour_l_image_preview2():
    """L'executable corrige aussi l'ancienne image admin deja publiee.

    Celle-ci utilisait ``api_key`` pour DroppedNeedle, tandis que le pre-semis
    et les autres clients utilisent ``password``.
    """
    from plugarr import remote_install

    instance = SimpleNamespace(api_key="ancienne-copie", password="cle-pre-semee")
    cfg = SimpleNamespace(services={"sabnzbd": instance})
    scope = {"__name__": "remote_test"}
    exec(remote_install.REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102

    scope["align_sabnzbd_key"](cfg)

    assert instance.api_key == "cle-pre-semee"
    assert instance.password == "cle-pre-semee"


def test_entree_distante_ne_reprend_droppedneedle_qu_apres_login_confirme(
    tmp_path, monkeypatch
):
    from plugarr import migrations, remote_install
    from plugarr.clients import droppedneedle
    from plugarr.clients.base import WiringError

    (tmp_path / ".stack-before-remote-original.yml").write_text("backup", encoding="utf-8")
    instance = SimpleNamespace(
        username="plugarr",
        password="nouveau",
        url=lambda _host: "http://nas:8688",
    )
    cfg = SimpleNamespace(
        services={"droppedneedle": instance}, username="plugarr", host="nas"
    )
    previous = SimpleNamespace(
        services={"droppedneedle": SimpleNamespace(username="ancien", password="bon")},
        username="ancien",
    )
    monkeypatch.setattr(migrations, "lire", lambda _path: (previous, []))
    attempts = []

    class FakeClient:
        def __init__(self, _url):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            pass

        needs_setup = False

        def login(self, username, password):
            attempts.append((username, password))
            if password != "bon":
                raise WiringError("connexion refusee", "HTTP 401")

    monkeypatch.setattr(droppedneedle, "DroppedNeedleClient", FakeClient)
    scope = {"__name__": "remote_test"}
    exec(remote_install.REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102

    scope["reuse_droppedneedle_account"](cfg, tmp_path)

    assert attempts == [("plugarr", "nouveau"), ("ancien", "bon")]
    assert (instance.username, instance.password) == ("ancien", "bon")


def test_entree_distante_reprend_audiobookshelf_seulement_si_le_compte_fonctionne(
    tmp_path, monkeypatch
):
    from plugarr import migrations, remote_install
    from plugarr.clients import audiobookshelf
    from plugarr.clients.base import WiringError

    (tmp_path / ".stack-before-remote-original.yml").write_text("backup", encoding="utf-8")
    instance = SimpleNamespace(
        username="plugarr", password="nouveau", url=lambda _host: "http://nas:13378"
    )
    cfg = SimpleNamespace(
        services={"audiobookshelf": instance}, username="plugarr", host="nas"
    )
    previous = SimpleNamespace(
        services={"audiobookshelf": SimpleNamespace(username="ancien", password="bon")},
        username="ancien",
    )
    monkeypatch.setattr(migrations, "lire", lambda _path: (previous, []))
    attempts = []

    class FakeClient:
        def __init__(self, _url):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            pass

        needs_setup = False

        def login(self, username, password):
            attempts.append((username, password))
            if password != "bon":
                raise WiringError("connexion refusee", "HTTP 401")

    monkeypatch.setattr(audiobookshelf, "AudiobookshelfClient", FakeClient)
    scope = {"__name__": "remote_test"}
    exec(remote_install.REMOTE_ENTRYPOINT.rsplit("raise SystemExit(main())", 1)[0], scope)  # noqa: S102

    scope["reuse_audiobookshelf_account"](cfg, tmp_path)

    assert attempts == [("plugarr", "nouveau"), ("ancien", "bon")]
    assert (instance.username, instance.password) == ("ancien", "bon")


def test_connecteur_charge_la_cle_privee_depuis_la_memoire(monkeypatch):
    calls: dict[str, object] = {}

    class FakeKey:
        fingerprint = "SHA256:cle-distante"

    class FakeRSAKey:
        @classmethod
        def from_private_key(cls, stream, password=None):
            calls["key_text"] = stream.read()
            calls["passphrase"] = password
            return FakeKey()

    class FakeClient:
        def set_missing_host_key_policy(self, policy):
            calls["policy"] = type(policy).__name__

        def connect(self, **kwargs):
            calls["connect"] = kwargs

        def get_transport(self):
            return SimpleNamespace(get_remote_server_key=lambda: FakeKey())

        def close(self):
            calls["closed"] = True

    fake_paramiko = SimpleNamespace(
        SSHClient=FakeClient,
        AutoAddPolicy=type("AutoAddPolicy", (), {}),
        RSAKey=FakeRSAKey,
        ECDSAKey=type("ECDSAKey", (), {}),
        Ed25519Key=type("Ed25519Key", (), {}),
        SSHException=RuntimeError,
    )
    monkeypatch.setitem(__import__("sys").modules, "paramiko", fake_paramiko)

    session = connect_paramiko(
        RemoteTarget(host="nas.local", port=2222, username="yannick"),
        RemoteCredentials(
            private_key="-----BEGIN PRIVATE KEY-----\nsecret-key\n-----END PRIVATE KEY-----",
            passphrase="phrase-secrete",
        ),
    )

    assert session.fingerprint == "SHA256:cle-distante"
    assert calls["key_text"] == (
        "-----BEGIN PRIVATE KEY-----\nsecret-key\n-----END PRIVATE KEY-----"
    )
    assert calls["passphrase"] == "phrase-secrete"
    assert calls["connect"]["hostname"] == "nas.local"
    assert calls["connect"]["port"] == 2222
    assert calls["connect"]["allow_agent"] is False
    assert calls["connect"]["look_for_keys"] is False


def test_deploy_utilise_sudo_sans_mettre_son_mot_de_passe_dans_la_commande():
    class SudoSession(DeploySession):
        def __post_init__(self):
            super().__post_init__()
            self.stdin_values: list[bytes | None] = []
            self.prepares = 0

        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            self.stdin_values.append(stdin)
            if "stat -c %g /var/run/docker.sock" in command:
                self.prepares += 1
                if self.prepares == 1:
                    return 1, "", "Permission denied"
                return 0, "sock_gid=998\n", ""
            return 0, '{"kind":"done","status":"done"}', ""

    session = SudoSession()
    deploy(
        RemoteTarget(
            host="nas.local",
            username="yannick",
            expected_fingerprint=session.fingerprint,
        ),
        RemoteCredentials(password="ssh-secret", sudo_password="sudo-secret"),
        RemoteDeployment(
            project_dir="/volume1/docker/plugarr",
            config_root="/volume1/docker/plugarr/config",
            data_root="/volume1/data",
            uid=1000,
            gid=10,
            stack_yaml="version: 1\nservices: {}\n",
            image="ghcr.io/example/plugarr:test",
        ),
        connect=lambda *_: session,
    )

    assert session.stdin_values[1] == b"sudo-secret\n"
    assert "sudo -S" in session.commands[1]
    assert "sudo-secret" not in repr(session.commands)
    docker_command = session.commands[-1]
    assert "--user 1000:10" not in docker_command


def test_deploy_peut_actualiser_la_passerelle_distante_sans_reinstaller_la_stack():
    class ActionSession(DeploySession):
        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            if "stat -c %g /var/run/docker.sock" in command:
                return 0, "sock_gid=998\n", ""
            return (
                0,
                (
                    '{"kind":"remote_access","result":{"status":"connected"}}\n'
                    '{"kind":"done","status":"done"}'
                ),
                "",
            )

    session = ActionSession()
    result = deploy(
        RemoteTarget(
            host="nas.local",
            username="yannick",
            expected_fingerprint=session.fingerprint,
        ),
        RemoteCredentials(password="secret"),
        RemoteDeployment(
            project_dir="/home/yannick/plugarr",
            config_root="/home/yannick/plugarr/config",
            data_root="/home/yannick/data",
            uid=1000,
            gid=100,
            stack_yaml="version: 1\nservices: {}\n",
            image="ghcr.io/example/plugarr:test",
        ),
        connect=lambda *_: session,
        operation="inspect",
    )

    assert result.status == "done"
    assert session.commands[-1].endswith("/home/yannick/plugarr inspect")


def test_deploy_refuse_d_ecraser_une_autre_stack_distante():
    class ExistingSession(DeploySession):
        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            return 0, "sock_gid=998\nstack_sha=deadbeef\n", ""

    session = ExistingSession()
    with pytest.raises(RuntimeError, match="pile distante existe deja"):
        deploy(
            RemoteTarget(
                host="nas.local",
                username="yannick",
                expected_fingerprint=session.fingerprint,
            ),
            RemoteCredentials(password="secret"),
            RemoteDeployment(
                project_dir="/home/yannick/plugarr",
                config_root="/home/yannick/plugarr/config",
                data_root="/home/yannick/data",
                uid=1000,
                gid=100,
                stack_yaml="version: 1\nservices: {}\n",
                image="ghcr.io/example/plugarr:test",
            ),
            connect=lambda *_: session,
        )

    assert session.files == {}


def test_deploy_remplace_une_pile_plugarr_apres_confirmation_et_controle_du_hash():
    class ExistingPlugArrSession(DeploySession):
        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            if "stat -c %g /var/run/docker.sock" in command:
                return 0, "sock_gid=998\nstack_sha=ancien-hash\nstack_managed=1\n", ""
            return 0, '{"kind":"done","status":"done"}', ""

    session = ExistingPlugArrSession()
    result = deploy(
        RemoteTarget(
            host="nas.local",
            username="yannick",
            expected_fingerprint=session.fingerprint,
        ),
        RemoteCredentials(password="secret"),
        RemoteDeployment(
            project_dir="/home/yannick/plugarr",
            config_root="/home/yannick/plugarr/config",
            data_root="/home/yannick/data",
            uid=1000,
            gid=100,
            stack_yaml="version: 1\nservices: {}\n",
            image="ghcr.io/example/plugarr:test",
            replace_existing=True,
            expected_existing_sha="ancien-hash",
        ),
        connect=lambda *_: session,
    )

    assert result.status == "done"
    assert "/home/yannick/plugarr/stack.yml" in session.files
    assert any(".stack-before-remote-ancien-hash.yml" in command for command in session.commands)


def test_deploy_refuse_si_la_pile_change_apres_la_confirmation():
    class ChangedSession(DeploySession):
        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            return 0, "sock_gid=998\nstack_sha=nouveau-hash\nstack_managed=1\n", ""

    session = ChangedSession()
    with pytest.raises(RuntimeError, match="change depuis la verification"):
        deploy(
            RemoteTarget(
                host="nas.local",
                username="yannick",
                expected_fingerprint=session.fingerprint,
            ),
            RemoteCredentials(password="secret"),
            RemoteDeployment(
                project_dir="/home/yannick/plugarr",
                config_root="/home/yannick/plugarr/config",
                data_root="/home/yannick/data",
                uid=1000,
                gid=100,
                stack_yaml="version: 1\nservices: {}\n",
                image="ghcr.io/example/plugarr:test",
                replace_existing=True,
                expected_existing_sha="ancien-hash",
            ),
            connect=lambda *_: session,
        )


def test_reset_distant_sauvegarde_et_recontrole_meme_si_stack_identique():
    stack = "version: 1\nservices: {}\n"
    old_sha = hashlib.sha256(stack.encode()).hexdigest()

    class ExistingSession(DeploySession):
        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            if "stat -c %g /var/run/docker.sock" in command:
                return 0, f"sock_gid=998\nstack_sha={old_sha}\nstack_managed=1\n", ""
            if "cp " in command:
                return 0, "", ""
            return 0, '{"kind":"done","status":"done"}', ""

    session = ExistingSession()
    deployment = RemoteDeployment(
        project_dir="/home/yannick/plugarr",
        config_root="/home/yannick/plugarr/config",
        data_root="/home/yannick/data",
        uid=1000,
        gid=100,
        stack_yaml=stack,
        image="ghcr.io/example/plugarr:test",
        reset_existing=True,
        expected_existing_sha=old_sha,
    )
    result = deploy(
        RemoteTarget(host="nas.local", username="yannick", expected_fingerprint=session.fingerprint),
        RemoteCredentials(password="secret"),
        deployment,
        connect=lambda *_: session,
    )

    assert result.status == "done"
    assert any(".stack-before-remote-" in command and "cp " in command for command in session.commands)
    assert session.commands[-1].endswith(
        f"reset-install {old_sha} ghcr.io/example/plugarr:test"
    )

    changed = ExistingSession()
    with pytest.raises(RuntimeError, match="change depuis la verification"):
        deploy(
            RemoteTarget(host="nas.local", username="yannick", expected_fingerprint=changed.fingerprint),
            RemoteCredentials(password="secret"),
            deployment.__class__(**{**deployment.__dict__, "expected_existing_sha": "0" * 64}),
            connect=lambda *_: changed,
        )
    assert changed.files == {}


def test_essai_vpn_s_execute_sur_le_docker_distant_sans_secret_dans_la_commande():
    class VpnSession(DeploySession):
        def run(self, command: str, *, stdin: bytes | None = None):
            self.commands.append(command)
            if "stat -c" in command:
                return 0, "sock_gid=998\n", ""
            if command.startswith("docker run"):
                return (
                    0,
                    '{"name":"Essai VPN","ok":true,"detail":"tunnel distant etabli","blocking":false}\n',
                    "",
                )
            if command.startswith("rm -f"):
                return 0, "", ""
            raise AssertionError(command)

    session = VpnSession()
    result = run_remote_vpn_test(
        RemoteTarget(
            host="nas.local",
            username="yannick",
            expected_fingerprint=session.fingerprint,
        ),
        RemoteCredentials(password="secret-ssh"),
        {
            "enabled": True,
            "provider": "protonvpn",
            "vpn_type": "wireguard",
            "wireguard_private_key": "cle-wireguard-secrete",
            "countries": "France",
        },
        uid=1000,
        gid=100,
        admin_image="ghcr.io/example/plugarr:admin",
        gluetun_image="qmcgaw/gluetun:v3.41.3",
        connect=lambda *_: session,
    )

    assert result["ok"] is True
    assert result["detail"] == "tunnel distant etabli"
    assert any(path.startswith("/tmp/.plugarr-vpn-test-") for path in session.files)
    assert all(mode == 0o600 for _, mode in session.files.values())
    assert "cle-wireguard-secrete" not in repr(session.commands)
    assert "secret-ssh" not in repr(session.commands)
    assert session.commands[-1].startswith("rm -f")


def test_connect_paramiko_absent_donne_un_message_clair(monkeypatch):
    """EXE reel du 25/09/2026 compile sans paramiko : erreur 500 muette."""
    monkeypatch.setitem(sys.modules, "paramiko", None)

    with pytest.raises(ValueError, match="paramiko"):
        connect_paramiko(
            RemoteTarget(host="vps.example", port=22, username="ubuntu"),
            RemoteCredentials(private_key="cle"),
        )


class NatProbeSession(ProbeSession):
    """VPS Oracle reel du 25/09/2026 : IP publique traduite, 10.0.0.30 local."""

    def run(self, _command: str, *, stdin: bytes | None = None):
        return (
            0,
            (
                "system=Linux\nmachine=aarch64\nuid=1001\ngid=1001\nhome=/home/ubuntu\n"
                "docker=29.1.3\naddresses=10.0.0.30 172.17.0.1 172.18.0.1 \n"
                "route_address=10.0.0.30\n"
            ),
            "",
        )


def test_probe_propose_l_adresse_privee_quand_l_ip_ssh_est_traduite():
    result = probe(
        RemoteTarget(host="203.0.113.10", port=22, username="ubuntu"),
        RemoteCredentials(private_key="cle"),
        connect=lambda *_: NatProbeSession(),
    )

    assert result.addresses == ("10.0.0.30", "172.17.0.1", "172.18.0.1")
    assert result.suggested_host("203.0.113.10") == "10.0.0.30"


def test_probe_garde_l_adresse_ssh_portee_par_la_machine_ou_un_nom_dns():
    result = probe(
        RemoteTarget(host="10.0.0.30", port=22, username="ubuntu"),
        RemoteCredentials(private_key="cle"),
        connect=lambda *_: NatProbeSession(),
    )

    assert result.suggested_host("10.0.0.30") == "10.0.0.30"
    assert result.suggested_host("nas.local") == "nas.local"


def test_probe_sans_adresses_connues_garde_l_adresse_ssh():
    result = probe(
        RemoteTarget(host="nas.local", port=22, username="yannick"),
        RemoteCredentials(password="secret"),
        connect=lambda *_: ProbeSession(),
    )

    assert result.suggested_host("192.168.1.50") == "192.168.1.50"


def test_deploy_impose_a_la_console_l_image_qui_installe():
    """VPS reel du 25/09/2026 : console epinglee sur l'image precedente, sans
    Shelfarr, qui plantait a chaque connexion (`service inconnu: 'shelfarr'`)."""
    session = DeploySession()
    deployment = RemoteDeployment(
        project_dir="/home/ubuntu/plugarr",
        config_root="/home/ubuntu/plugarr/config",
        data_root="/home/ubuntu/data",
        uid=1001,
        gid=1001,
        stack_yaml="version: 1\nservices: {}\n",
        image="ghcr.io/example/plugarr:n-admin@sha256:aaa",
        veille_image="ghcr.io/example/plugarr:n@sha256:bbb",
    )

    deploy(
        RemoteTarget(host="10.0.0.30", username="ubuntu", expected_fingerprint=session.fingerprint),
        RemoteCredentials(private_key="cle"),
        deployment,
        connect=lambda *_: session,
        on_event=lambda _event: None,
    )

    run = next(c for c in session.commands if c.startswith("docker run") or " docker run " in c)
    assert "-e PLUGARR_CONSOLE_IMAGE=ghcr.io/example/plugarr:n-admin@sha256:aaa" in run
    assert "-e PLUGARR_VEILLE_IMAGE=ghcr.io/example/plugarr:n@sha256:bbb" in run
    entree = session.files["/home/ubuntu/plugarr/.plugarr-remote-entry.py"][0].decode()
    assert 'setattr(orchestrator.catalog, _nom, os.environ["PLUGARR_" + _nom])' in entree
