// Browser checks for the standalone preview. Requires Playwright and Chromium.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const {pathToFileURL} = require('node:url');

(async () => {
  const browser = await chromium.launch({headless:true});
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'plugarr-remote-preview-'));
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
    const errors = [], external = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', r => { if (/^https?:/.test(r.url())) external.push(r.url()); });
    await page.goto(pathToFileURL(path.resolve('previews/acces-distant.html')).href);
    const click = id => page.locator('#'+id).click();
    const panel = async step => assert.equal(await page.locator(`[data-panel="${step}"]`).isVisible(),true);
    const generate = async () => { await click('setup-next'); await page.locator('#confirm').check(); await click('generate'); await panel(3); };
    await panel(0);
    await click('choose-next');
    assert.equal(await page.locator('#setup-next').isDisabled(),true);
    await click('associate');
    await generate();
    assert.equal(await page.locator('.access-card').count(),3);
    await click('mobile-open');
    assert.match(await page.locator('#mobile-fields').innerText(),/100\.101\.102\.103/);
    await page.selectOption('#mobile-client','qbremote');
    assert.equal(await page.locator('#mobile-service').inputValue(),'qbittorrent');
    assert.match(await page.locator('#mobile-fields').innerText(),/8080/);
    assert.equal(await page.locator('#mobile-fields input[type=password]').count(),1);
    await page.locator('#mobile-fields').getByRole('button',{name:'Afficher',exact:true}).click();
    assert.equal(await page.locator('#mobile-fields input[type=text]').count(),1);
    await page.selectOption('#mobile-network','local');
    assert.match(await page.locator('#mobile-fields').innerText(),/192\.0\.2\.50/);
    await page.getByText('Essayer un résultat de connexion',{exact:true}).click();
    await click('phone-fail');
    assert.match(await page.locator('#phone-result').innerText(),/Échec simulé/);

    await click('restart');
    await page.locator('[name=method][value=https]').check();
    await click('choose-next');
    await page.fill('#domain','https://bad.example/path');
    await click('check-domain');
    assert.equal(await page.locator('#domain-error').isVisible(),true);
    await page.fill('#domain','maison.example');
    await page.getByText('Scénarios à essayer',{exact:true}).click();
    for (const scenario of ['dns','ports','proxy','cgnat']) {
      await page.selectOption('#scenario',scenario);
      await click('check-domain');
      assert.equal(await page.locator('#setup-next').isDisabled(),true);
      assert.equal(await page.locator('#domain-status').isVisible(),true);
    }
    await page.locator('#domain-status').getByRole('button',{name:'Utiliser Tailscale'}).click();
    assert.equal(await page.locator('#tailscale-setup').isVisible(),true);
    assert.equal(await page.locator('#setup-next').isDisabled(),true);
    await click('restart');
    await page.locator('[name=method][value=https]').check();
    await click('choose-next');
    await page.getByRole('checkbox',{name:'Publier Radarr'}).uncheck();
    await click('check-domain');
    await page.fill('#domain','autre.example');
    assert.equal(await page.locator('#setup-next').isDisabled(),true);
    await click('check-domain');
    await generate();
    await click('mobile-open');
    assert.match(await page.locator('#mobile-fields').innerText(),/https:\/\/sonarr\.autre\.example/);
    assert.match(await page.locator('#mobile-fields').innerText(),/443/);
    await page.selectOption('#mobile-service','radarr');
    assert.equal(await page.locator('#mobile-network option').count(),1);
    assert.match(await page.locator('#mobile-fields').innerText(),/7878/);
    await page.selectOption('#mobile-service','sonarr');
    await page.selectOption('#mobile-network','remote');
    const downloading = page.waitForEvent('download');
    await click('mobile-download');
    const downloaded = await downloading;
    const output = path.join(temp,downloaded.suggestedFilename());
    await downloaded.saveAs(output);
    await page.goto(pathToFileURL(output).href);
    await panel(3);
    assert.match(await page.locator('#access-cards').innerText(),/sonarr\.autre\.example/);
    assert.equal(await page.locator('#access-cards input[type=password]').count(),5);
    await click('mobile-open');
    assert.match(await page.locator('#mobile-fields').innerText(),/443/);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    if(process.env.PREVIEW_SCREENSHOT)await page.screenshot({path:process.env.PREVIEW_SCREENSHOT,fullPage:true});
    await click('restart');
    await page.locator('[name=method][value=local]').check();
    await click('choose-next');
    await generate();
    await click('mobile-open');
    assert.equal(await page.locator('#mobile-network option').count(),1);
    assert.equal(await page.locator('#mobile-network').inputValue(),'local');
    await page.setViewportSize({width:320,height:700});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    assert.deepEqual(errors,[]);
    assert.deepEqual(external,[]);
    console.log('PASS: local, Tailscale, HTTPS, network failures, domain validation, stale state, mobile credentials, standalone export, 390/320px layouts, no external requests.');
    console.log('Export tested at: '+output);
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
